services:
  - type: web
    name: spindraw
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        value: https://spin-22w3.onrender.com
      - key: FIREBASE_PROJECT_ID
        value: spindraw-6cdb2
      - key: FIREBASE_SERVICE_ACCOUNT_B64
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PAYPAL_MODE
        value: sandbox
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: ADMIN_USERNAME
        value: adminspin
      - key: ADMIN_EMAIL
        sync: false
    autoDeploy: true
    regions:
      - oregon
    healthCheckPath: /
    routes:
      - type: rewrite
        source: /privacidad.html
        destination: /privacidad.html
      - type: rewrite
        source: /privacidad-en.html
        destination: /privacidad-en.html
      - type: rewrite
        source: /privacidad-pt.html
        destination: /privacidad-pt.html
      - type: rewrite
        source: /terminos.html
        destination: /terminos.html
      - type: rewrite
        source: /terminos-en.html
        destination: /terminos-en.html
      - type: rewrite
        source: /terminos-pt.html
        destination: /terminos-pt.html
      - type: rewrite
        source: /cookies.html
        destination: /cookies.html
      - type: rewrite
        source: /cookies-en.html
        destination: /cookies-en.html
      - type: rewrite
        source: /cookies-pt.html
        destination: /cookies-pt.html
      - type: rewrite
        source: /contacto.html
        destination: /contacto.html
      - type: rewrite
        source: /contacto-en.html
        destination: /contacto-en.html
      - type: rewrite
        source: /contacto-pt.html
        destination: /contacto-pt.html
      - type: rewrite
        source: /contacto.html
        destination: /contacto.html
      - type: rewrite
        source: /*
        destination: /ruleta-pro.html
