services:
  - type: web
    name: spindraw
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3000
      - key: FRONTEND_URL
        sync: false
      - key: FIREBASE_PROJECT_ID
        value: spindraw-6cdb2
      - key: FIREBASE_SERVICE_ACCOUNT_B64
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PAYPAL_MODE
        value: sandbox
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: ADMIN_USERNAME
        value: adminspin
      - key: ADMIN_EMAIL
        sync: false
    autoDeploy: true
    regions:
      - oregon
    healthCheckPath: /
    routes:
      - type: rewrite
        source: /*
        destination: /ruleta-pro.html
